# Generated by Django 4.0.3 on 2022-04-01 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('articul', models.CharField(max_length=255, unique=True)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('size', models.TextField()),
                ('material_composition', models.TextField()),
                ('quantity_in_one_line', models.IntegerField()),
                ('fabric', models.CharField(max_length=255)),
                ('is_hit_of_sales', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.collection')),
                ('colors', models.ManyToManyField(to='main.color')),
            ],
        ),
    ]
