# Generated by Django 4.0.3 on 2022-04-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
