# Generated by Django 4.0.3 on 2022-04-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_news_options_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='help_images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('id',), 'verbose_name_plural': 'Новости'},
        ),
    ]
