# Generated by Django 4.0.3 on 2022-04-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_publicoffer_alter_aboutus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=20)),
                ('telegram', models.CharField(max_length=20, verbose_name='Номер в телеграм')),
            ],
            options={
                'verbose_name': 'Наши контакты',
                'verbose_name_plural': 'Наши контакты',
            },
        ),
        migrations.AlterModelOptions(
            name='publicoffer',
            options={'verbose_name': 'Публичная оферта', 'verbose_name_plural': 'Публичная оферта'},
        ),
    ]
