# Generated by Django 4.0.3 on 2022-04-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_callbackrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbackrequest',
            options={'verbose_name': 'Обратный звонок', 'verbose_name_plural': 'Обратные звонки'},
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='did_callback',
            field=models.CharField(choices=[('Y', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='type_of_appeal',
            field=models.CharField(default='Обратный звонок', max_length=255),
        ),
    ]
