# Generated by Django 4.0.3 on 2022-04-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_slider_alter_callbackrequest_did_callback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='url',
        ),
    ]
