# Generated by Django 4.0.3 on 2022-04-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_favourites',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
