# Generated by Django 4.0.3 on 2022-04-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_customuser_order_orderitems_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
