# Generated by Django 4.0.3 on 2022-04-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_cart_total_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_total_sum',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
    ]
