# Generated by Django 4.0.3 on 2022-04-20 05:37

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_cart_final_total_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='rgb',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
